# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrfid',
            name='rfid_no',
        ),
        migrations.RemoveField(
            model_name='userrfid',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rfid_list',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.DeleteModel(
            name='UserRfid',
        ),
    ]
