# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdetails', '0002_auto_20170329_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdetails.RfidCar', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rfid_list',
        ),
    ]
