# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0005_auto_20170329_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
    ]
