# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0006_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.9)]),
        ),
    ]
