# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0010_tollplaza_toll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollplaza',
            name='car_jeep_van_toll',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='heavy_vehicle_toll',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='lcv_minibus_toll',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='three_wheeler_toll',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='truck_bus_toll',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tollplaza',
            name='two_wheeler_toll',
            field=models.IntegerField(max_length=3),
        ),
    ]
