# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0011_auto_20170331_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollplaza',
            name='two_wheeler_toll',
        ),
    ]
