# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdetails', '0013_auto_20170331_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[(b'Credit', b'Credit'), (b'Debit', b'Debit')], max_length=30)),
                ('transaction_date_time', models.DateTimeField(default=datetime.datetime(2017, 3, 31, 19, 57, 37, 973000))),
                ('recipient', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userdetails.Wallet')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_balance',
        ),
    ]
