# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0015_auto_20170331_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 20, 1, 11, 229000)),
        ),
    ]
